#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check CI scripts
      run: shellcheck .github/scripts/*

    - name: Check source files
      run: |
        shellcheck src/*
        .github/scripts/stylecheck src/*

    - name: Check GitPack files
      run: shellcheck .gitpack/install/global-Linux/p*
