#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/*

    - name: Check GitPack files
      run: shellcheck .gitpack/install/global-Linux/p*
